### ISSUE TITLE
Graceful container shutdown

### ISSUE THREAD

**Issue by maslick** [corretto/corretto-11-docker#8]
For our java services running in k8s we are using the following ``preStop`` hook:
```
lifecycle:
   preStop:
     exec:
       command: ["/bin/bash", "-c", "PID=`pidof java` && kill -SIGTERM $PID && while ps -p $PID > /dev/null; do sleep 1; done;"]
```
However, both ``pidof`` and ``ps`` executables are missing in the official Docker image. I have created a PR and added the missing packages. If there is a more "lightweight" way of achieving the same, let me know. Thanks :)
